# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BlackHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'AeroGearHttp'
	pod 'AeroGearOAuth2'
  # Pods for BlackHelper

  target 'BlackHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlackHelperUITests' do
    # Pods for testing
  end

end
